FROM python:3.13

WORKDIR /home/app

# Install dependencies
COPY requirements/local.txt ./requirements/local.txt
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements/local.txt

# Copy the application code
COPY . .

# Run migrations and index building
RUN python manage.py makemigrations --no-input
RUN python manage.py migrate --no-input

# Expose the port the app runs on
EXPOSE 8000

# Command to run the appplication
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
