"""
Django settings for prismasettings project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
import mimetypes


load_dotenv()  # Esto carga las variables del archivo .env a os.environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Para subir y ver archivos media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']

RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.core.apps.CoreConfig',
    'apps.Admin.apps.AdminConfig',
    'apps.detalles.apps.DetallesConfig',
    'apps.Profesores.apps.ProfesoresConfig',
    'apps.estudiantes.apps.EstudiantesConfig',
    'django_bootstrap5',
    'django_cleanup.apps.CleanupConfig', # Módulo para limpiar en disco las actualizaciones de archivos cuando se les reemplaza por otro.
    'haystack', # Módulo de búsqueda
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prismasettings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'apps.core.utils.context_processors.roles_usuario',
                'apps.core.utils.context_processors.notificaciones_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'prismasettings.wsgi.application'
LOGIN_URL = 'login'

# 1. Definir y crear automáticamente el directorio en el servidor
WHOOSH_INDEX_PATH = os.path.join(BASE_DIR, 'whoosh_index')
os.makedirs(WHOOSH_INDEX_PATH, exist_ok=True)

# 2. Configuración de conexión de Haystack
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': WHOOSH_INDEX_PATH,
    },
}

# 3. Procesador de señales
# 3. Procesador de señales (Desactivado para que no rompa la DB)
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.BaseSignalProcessor'
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 12

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ---------------------------------------------------------
# CONFIGURACIÓN DE SUPABASE STORAGE (NATIVO - PRODUCCIÓN)
# ---------------------------------------------------------
SUPABASE_URL = "https://ajkmhzxofqeqrtmbvcyk.supabase.co" # Tu URL base de Supabase
SUPABASE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
SUPABASE_BUCKET = os.getenv('SUPABASE_BUCKET_NAME')
SUPABASE_STATIC_BUCKET = os.getenv('SUPABASE_BUCKET_NAME')
SUPABASE_MEDIA_BUCKET = os.getenv('SUPABASE_BUCKET_NAME')

STORAGES = {
    "default": {
        # Los archivos subidos por los usuarios (Media) van a Supabase
        "BACKEND": "django_supabase_storage.SupabaseStorage",
    },
    "staticfiles": {
        # Los CSS, JS y Bootstrap los sirve WhiteNoise directamente en Render
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Configuración de tipos MIME para archivos de video
mimetypes.add_type("video/mp4", ".mp4", True)
mimetypes.add_type("video/webm", ".webm", True)

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

#modelos de autentificacion de usuario
AUTH_USER_MODEL = 'core.Usuario'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

BOOTSTRAP5 = {
    "css_url": {
        "url": "/static/bootstrap/css/bootstrap.min.css",
    },
    "javascript_url": {
        "url": "/static/bootstrap/js/bootstrap.bundle.min.js",
    },
    "theme_url": None,
}

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# 2. Esto le dice a Django que busque en las carpetas "static" de cada APP
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Le dice a django que busque primero en la carpeta static del proyecto si no lo encuentra va hacia la carpeta static de cada app
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), 
]

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('PRISMA_GMAIL_ADDRESS') #dirección de correo electrónico
EMAIL_HOST_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD') #contraseña de correo electrónico
DEFAULT_FROM_EMAIL = os.environ.get('PRISMA_GMAIL_ADDRESS') # Correo que aparecerá como remitente
SITE_NAME = 'Prisma' # Nombre del sitio web para usar en los correos
EMAIL_TIMEOUT = 10 # Tiempo de espera para la conexión SMTP en segundos

# Redirecciones de autenticación
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

#------------Código para cerrar sesión por inactividad o cerrar pestaña-------------#
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# La sesión expira en 3600 segundos (1 hora)
SESSION_COOKIE_AGE = 3600
# El contador se reinicia cada vez que el usuario hace algo
SESSION_SAVE_EVERY_REQUEST = True

